#!/usr/bin/env node
// Generates docs/ARCHITECTURE.md from site/ and widget/ directories.
// Run: npm run arch

import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, sep } from 'node:path';

const ROOTS = ['site', 'widget', 'supabase'];
const BIG = 500;
const SKIP = new Set(['node_modules', '.next', '.git', 'dist', 'build', '.temp']);
const posix = (p) => p.split(sep).join('/');
const lines = (f) => readFileSync(f, 'utf8').split(/\r?\n/);

function walk(dir, out = []) {
  if (!existsSync(dir)) return out;
  for (const n of readdirSync(dir)) {
    if (SKIP.has(n)) continue;
    const p = join(dir, n);
    statSync(p).isDirectory() ? walk(p, out) : out.push(p);
  }
  return out;
}

const allFiles = ROOTS.flatMap((r) => walk(r));
const codeFiles = allFiles.filter((f) => /\.(ts|tsx|js|jsx)$/.test(f));

const big = codeFiles
  .map((f) => ({ f, src: lines(f) }))
  .filter((x) => x.src.length > BIG)
  .sort((a, b) => b.src.length - a.src.length);

const out = [];
out.push('# ARCHITECTURE.md (generated by `npm run arch`; do not edit by hand)', '');
out.push('Read this before searching. Open files by line range. Never read a "Big file" whole.', '');

out.push('## 1. Directory Overview');
out.push('| Component | Location | Role |');
out.push('|---|---|---|');
out.push('| 1-Page Studio Site | `site/` | Next.js 15 client website |');
out.push('| Embeddable Widget | `widget/` | Standalone embeddable modal |');
out.push('| Database & Backend | `supabase/` | Migrations, Edge Functions, RLS |');
out.push('| Documentation | `docs/` | Agency runbooks and token rules |');

out.push('', '## 2. Key Code Files');
for (const f of codeFiles.slice(0, 30)) {
  const p = posix(f);
  out.push(`- \`${p}\` (${lines(f).length} lines)`);
}

out.push('', `## 3. Big files (over ${BIG} lines: use line ranges)`);
if (!big.length) {
  out.push('None. All files are clean and modular.');
} else {
  for (const { f, src } of big) {
    out.push(`### \`${posix(f)}\` (${src.length} lines)`);
  }
}

out.push('', '## 4. Sources of truth');
for (const f of ['site/src/config/client.ts', 'docs/DESIGN.md', 'docs/ONBOARDING.md', 'docs/ASSETS.md', 'docs/STATE.md', 'GEMINI.md']) {
  if (existsSync(f)) out.push(`- \`${f}\``);
}

writeFileSync('docs/ARCHITECTURE.md', out.join('\n') + '\n');
console.log(`docs/ARCHITECTURE.md written: ${codeFiles.length} source file(s), ${big.length} big file(s).`);
